### ISSUE TITLE
Some Reddit videos not working

### ISSUE THREAD

**Issue by gilnicki** [SB-Ansel/DuckDL#1]
**Version of DuckDL:** 1.4.0.2

When trying download some reddit videos, I get the following error after pressing "Start downloading Queue":

![image](https://user-images.githubusercontent.com/14282758/96970750-6c927980-1514-11eb-94ea-d486b43b2cf6.png)

Here two sample links:
- [amazing_3d_projection_at_brussels_airport](https://www.reddit.com/r/blackmagicfuckery/comments/jfb6sg/amazing_3d_projection_at_brussels_airport/)
- [my_brain_is_so_confused_right_now](https://www.reddit.com/r/blackmagicfuckery/comments/jgg4os/my_brain_is_so_confused_right_now/)

**Comment by SB-Ansel** [comment]
YouTube-dl is unable to determine video quality infomation from the host about this specific video. I believe this was a fixed issue (though not published) before the repo was taken down. In any case, I've tweaked the arguments which are passed to youtube-dl so pressing 'best' will have youtube-dl attempt to download in the best quality, failing that it will choose the second best option.

**Comment by SB-Ansel** [comment]
Fixed in latest release (1.4.3).
